name: Cleanup Neon Database

on:
  pull_request_target:
    types: [closed]

jobs:
  cleanup-database:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Bun.js
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.2.0

      - name: Install Vercel CLI
        run: bun install -g vercel

      - name: Delete Vercel Backend Preview Deployment
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          DEPLOY_ALIAS="penwwws-backend-from-frontend-pr-$PR_ID.vercel.app"
          echo "Deleting deployment with alias: $DEPLOYMENT_ALIAS"
          vercel remove $DEPLOY_ALIAS --token=${{ secrets.VERCEL_TOKEN }} --scope abdullah-abdulkareems-projects-0896f126 --yes

      - name: Delete Vercel Frontend Preview Deployment
        run: |
          PR_ID=${{ github.event.pull_request.number }}
          DEPLOY_ALIAS="penwwws-frontend-pr-$PR_ID.vercel.app"
          echo "Deleting deployment with alias: $DEPLOYMENT_ALIAS"
          vercel remove $DEPLOY_ALIAS --token=${{ secrets.VERCEL_TOKEN }} --scope abdullah-abdulkareems-projects-0896f126 --yes

      - name: Install Neon CLI
        run: bun install -g neonctl

      - name: Delete Neon Branch
        run: |
          BRANCH_NAME="pr-${{ github.event.pull_request.number }}"
          neonctl branches delete $BRANCH_NAME --api-key ${{ secrets.NEON_TOKEN }} \
            --project-id ${{ secrets.NEON_PROJECT_ID }}
