name: Deploy Preview (Backend + Frontend)

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    outputs:
      backend-url: ${{ steps.vercel-url.outputs.VERCEL_URL }}
    steps:
      - name: Checkout Backend Repository
        uses: actions/checkout@v4
        with:
          repository: Abdullah-988/penwwws-backend
          token: ${{ secrets.GITHUB_TOKEN }}
          path: backend

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache-dependency-path: ./backend/package-lock.json
          cache: "npm"

      - name: Install Backend Dependencies
        working-directory: ./backend
        run: npm install

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Install Neon CLI
        run: npm install -g neonctl

      - name: Create Neon Database Branch
        id: neon-branch
        if: github.event.action == 'opened' || github.event.pull_request.additions <= 1
        run: |
          # Create a new branch for the PR
          BRANCH_NAME="pr-${{ github.event.pull_request.number }}"
          neonctl branches create \
            --api-key ${{ secrets.NEON_TOKEN }} \
            --project-id ${{ secrets.NEON_PROJECT_ID }} \
            --name $BRANCH_NAME

          # Get the connection string for the new branch
          DB_URL=$(neonctl connection-string \
            --api-key ${{ secrets.NEON_TOKEN }} \
            --project-id ${{ secrets.NEON_PROJECT_ID }} \
            --branch $BRANCH_NAME)

          echo "DATABASE_URL=${DB_URL}" >> $GITHUB_ENV
          echo "::set-output name=DB_URL::${DB_URL}"

      - name: Generate JWT_SECRET
        id: jwt-secret
        run: |
          JWT_SECRET=$(openssl rand -base64 32)
          echo "JWT_SECRET=${JWT_SECRET}" >> $GITHUB_ENV
          echo "::set-output name=JWT_SECRET::${JWT_SECRET}"

      - name: Run Prisma Migrations and Seed
        working-directory: ./backend
        run: |
          npx prisma db push --force-reset
          npx prisma db seed

      - name: Pull Vercel Environment Information
        working-directory: ./backend
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        working-directory: ./backend
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Backend to Vercel (Preview)
        working-directory: ./backend
        id: vercel-url
        run: |
          # Deploy the backend to Vercel and capture the URL
          vercel deploy --prebuilt \
            --token=${{ secrets.VERCEL_TOKEN }} \
            --scope abdullah-abdulkareems-projects-0896f126 \
            --env DATABASE_URL=${{ env.DATABASE_URL }} \
            --env JWT_SECRET="${{ env.JWT_SECRET }}" \
            --env NODEMAILER_SERVICE=${{ secrets.NODEMAILER_SERVICE }} \
            --env NODEMAILER_EMAIL=${{ secrets.NODEMAILER_EMAIL }} \
            --env NODEMAILER_PASSWORD="${{ secrets.NODEMAILER_PASSWORD }}" \
            --yes &> vercel-output-backend
          BACKEND_URL=$(cat vercel-output-backend | grep 'Preview:' | awk '{print $2}')
          echo "VERCEL_URL=${BACKEND_URL}" >> $GITHUB_ENV
          echo "::set-output name=VERCEL_URL::${BACKEND_URL}"

  deploy-frontend:
    runs-on: ubuntu-latest
    permissions:
      pull-requests: write
    needs: deploy-backend
    steps:
      - name: Checkout Frontend Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: "npm"

      - name: Install Frontend Dependencies
        run: npm install

      - name: Install TailwindCSS Dependencies
        run: npm install lightningcss-linux-x64-gnu @tailwindcss/oxide-linux-x64-gnu sass-embedded-linux-x64

      - name: Install Vercel CLI
        run: npm install -g vercel@latest

      - name: Pull Vercel Environment Information
        run: vercel pull --yes --environment=preview --token=${{ secrets.VERCEL_TOKEN }}

      - name: Build Project Artifacts
        run: vercel build --token=${{ secrets.VERCEL_TOKEN }}

      - name: Deploy Frontend to Vercel (Preview)
        id: frontend-deploy
        run: |
          vercel deploy --prebuilt --token=${{ secrets.VERCEL_TOKEN }} \
            --scope abdullah-abdulkareems-projects-0896f126 \
            --env NEXT_PUBLIC_BACKEND_URL=${{ needs.deploy-backend.outputs.VERCEL_URL }} \
            --yes &> vercel-output-frontend
          FRONTEND_URL=$(cat vercel-output-frontend | grep 'Preview:' | awk '{print $2}')
          echo "Frontend deployed with backend URL: $FRONTEND_URL"
          echo "::set-output name=FRONTEND_URL::${FRONTEND_URL}"

      - name: Update Pull Request with Frontend Preview URL
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          # Get the current PR body
          PR_BODY=$(gh pr view ${{ github.event.pull_request.number }} --json body -q '.body')

          # Replace the live preview placeholder with the actual frontend preview URL
          FRONTEND_URL="${{ steps.frontend-deploy.outputs.FRONTEND_URL }}"
          UPDATED_BODY="${PR_BODY//<!--- live-Preview -->/${FRONTEND_URL}}"

          # Update the PR body with the new preview URL
          gh pr edit ${{ github.event.pull_request.number }} --body "$UPDATED_BODY"
